In [1]:
import pandas

data = pandas.read_csv("storms.csv", low_memory=False)

In [2]:
data

,Serial_Num,Season,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,...,jtwc_??_wrad34_rad3,jtwc_??_wrad34_rad4,jtwc_??_wrad50_rad1,jtwc_??_wrad50_rad2,jtwc_??_wrad50_rad3,jtwc_??_wrad50_rad4,jtwc_??_wrad64_rad1,jtwc_??_wrad64_rad2,jtwc_??_wrad64_rad3,jtwc_??_wrad64_rad4
0,1842298N11080,1842,1,NI,BB,NOT NAMED,1842-10-25 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,1842298N11080,1842,1,NI,BB,NOT NAMED,1842-10-25 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-25 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
5,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
6,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
7,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
8,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
11,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
12,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
14,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
15,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
17,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
18,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
20,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
21,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
22,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
24,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
25,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
26,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
27,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
28,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
29,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344776,2016040S17154,2016,2,SP,EA,TATIANA,2/10/2016 18:00,NR,-16.48,156.82,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344777,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 0:00,NR,-16.75,157.38,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344778,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 6:00,NR,-16.92,157.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344779,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 12:00,NR,-16.80,158.26,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344780,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 18:00,NR,-17.08,158.75,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344781,2016040S17154,2016,2,SP,EA,TATIANA,2/12/2016 0:00,NR,-17.23,159.38,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344782,2016040S17154,2016,2,SP,EA,TATIANA,2/12/2016 6:00,NR,-18.15,159.80,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344783,2016040S17154,2016,2,SP,MM,TATIANA,2/12/2016 12:00,NR,-18.95,160.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344784,2016040S17154,2016,2,SP,MM,TATIANA,2/12/2016 18:00,NR,-20.01,160.21,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344785,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 0:00,NR,-21.00,160.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344786,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 6:00,NR,-22.64,160.27,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344787,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 12:00,NR,-24.09,160.29,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344788,2016040S17154,2016,2,SP,EA,TATIANA,2/13/2016 18:00,NR,-25.32,159.71,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344789,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 0:00,NR,-26.02,159.20,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344790,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 6:00,NR,-26.00,159.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344791,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 12:00,NR,-25.60,158.65,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344792,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 18:00,NR,-25.20,158.30,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344793,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 0:00,NR,-24.80,158.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344794,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 6:00,NR,-24.40,158.70,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344795,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 12:00,NR,-24.20,158.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344796,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 0:00,NR,-15.50,137.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344797,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 6:00,NR,-15.80,137.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344798,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 12:00,NR,-15.90,136.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344799,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 18:00,NR,-15.80,137.20,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344800,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 0:00,NR,-15.80,137.80,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344801,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 6:00,NR,-15.50,137.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344802,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 12:00,NR,-15.60,138.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344803,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 18:00,NR,-16.00,139.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344804,2016074S16137,2016,3,SP,EA,NONAME,3/16/2016 0:00,NR,-16.40,140.30,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344805,2016074S16137,2016,3,SP,EA,NONAME,3/16/2016 6:00,NR,-16.55,141.10,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [3]:
data['Nature'].value_counts()

 TS    200117
 NR    124817
 ET     15378
 DS      3061
 SS      1291
 MX       142
Name: Nature, dtype: int64

In [4]:
TS = data.loc[data['Nature'] == " TS"]
TS = TS.reset_index(drop=True)
TS

,Serial_Num,Season,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,...,jtwc_??_wrad34_rad3,jtwc_??_wrad34_rad4,jtwc_??_wrad50_rad1,jtwc_??_wrad50_rad2,jtwc_??_wrad50_rad3,jtwc_??_wrad50_rad4,jtwc_??_wrad64_rad1,jtwc_??_wrad64_rad2,jtwc_??_wrad64_rad3,jtwc_??_wrad64_rad4
0,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-23 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-23 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
5,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
6,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 00:00:00,TS,28.0,-94.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
7,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 06:00:00,TS,28.0,-95.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
8,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 12:00:00,TS,28.0,-96.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 18:00:00,TS,28.1,-96.5,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 21:00:00,TS,28.2,-96.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
11,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 00:00:00,TS,28.2,-97.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
12,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 06:00:00,TS,28.3,-97.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 12:00:00,TS,28.4,-98.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
14,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 18:00:00,TS,28.6,-98.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
15,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 00:00:00,TS,29.0,-99.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 06:00:00,TS,29.5,-99.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
17,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 12:00:00,TS,30.0,-100.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
18,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 18:00:00,TS,30.5,-100.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-28 00:00:00,TS,31.0,-100.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
20,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-29 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
21,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-29 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
22,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-30 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-30 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
24,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-06-30 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
25,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-06-30 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
26,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-07-01 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
27,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-07-01 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
28,1851181N19275,1851,2,NA,GM,NOT NAMED,1851-07-01 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
29,1851181N19275,1851,2,NA,GM,NOT NAMED,1851-07-01 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200087,2015344N07145,2015,28,WP,MM,MELOR,12/13/2015 12:00,TS,12.4,128.1,...,80,125,70,60,60,80,35,30,30,35
200088,2015344N07145,2015,28,WP,MM,MELOR,12/13/2015 18:00,TS,12.5,126.9,...,90,135,80,60,60,80,35,30,30,35
200089,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 0:00,TS,12.5,125.8,...,75,110,80,60,60,80,35,30,30,35
200090,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 6:00,TS,12.6,124.6,...,75,110,80,60,60,80,35,30,30,35
200091,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 12:00,TS,12.8,123.5,...,75,110,80,60,60,80,35,30,30,35
200092,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 18:00,TS,12.9,122.6,...,75,110,65,65,65,65,25,25,25,25
200093,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 0:00,TS,13.0,121.8,...,75,110,65,65,65,65,25,25,25,25
200094,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 6:00,TS,13.2,121.2,...,75,110,65,65,65,65,20,20,20,20
200095,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 12:00,TS,13.4,120.6,...,75,110,65,65,65,65,20,20,20,20
200096,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 18:00,TS,13.7,120.1,...,90,110,65,50,50,65,-1,-1,-1,-1
200097,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 0:00,TS,14.1,120.1,...,75,95,-1,-1,-1,-1,-1,-1,-1,-1
200098,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 6:00,TS,14.1,120.3,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200099,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 12:00,TS,13.7,120.3,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200100,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 18:00,TS,13.1,120.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200101,2015344N07145,2015,28,WP,MM,MELOR,12/17/2015 0:00,TS,12.5,120.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200102,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/14/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200103,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/14/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200104,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/16/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200105,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/16/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200106,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 0:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200107,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 6:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200108,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200109,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200110,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 0:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200111,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 6:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200112,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 12:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200113,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 18:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200114,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 0:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200115,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 6:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200116,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 12:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [5]:
SpecificStorms = TS[TS['Serial_Num'].isin(['2005236N23285', '2005275N19274', '2004258N16300', '1998295N12284',
                                          '1994313N12278', '1979238N12324', '1974258N15295', '1963270N08327', '1900239N15318',
                                          '1935292N12281'])]

SpecificStorms

,Serial_Num,Season,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,...,jtwc_??_wrad34_rad3,jtwc_??_wrad34_rad4,jtwc_??_wrad50_rad1,jtwc_??_wrad50_rad2,jtwc_??_wrad50_rad3,jtwc_??_wrad50_rad4,jtwc_??_wrad64_rad1,jtwc_??_wrad64_rad2,jtwc_??_wrad64_rad3,jtwc_??_wrad64_rad4
23900,1900239N15318,1900,1,NA,NA,UNNAMED,8/27/1900 0:00,TS,15.0,-42.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23901,1900239N15318,1900,1,NA,NA,UNNAMED,8/27/1900 6:00,TS,15.2,-43.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23902,1900239N15318,1900,1,NA,NA,UNNAMED,8/27/1900 12:00,TS,15.3,-44.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23903,1900239N15318,1900,1,NA,NA,UNNAMED,8/27/1900 18:00,TS,15.4,-45.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23904,1900239N15318,1900,1,NA,NA,UNNAMED,8/28/1900 0:00,TS,15.6,-46.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23905,1900239N15318,1900,1,NA,NA,UNNAMED,8/28/1900 6:00,TS,15.8,-47.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23906,1900239N15318,1900,1,NA,NA,UNNAMED,8/28/1900 12:00,TS,16.0,-49.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23907,1900239N15318,1900,1,NA,NA,UNNAMED,8/28/1900 18:00,TS,16.1,-50.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23908,1900239N15318,1900,1,NA,NA,UNNAMED,8/29/1900 0:00,TS,16.3,-51.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23909,1900239N15318,1900,1,NA,NA,UNNAMED,8/29/1900 6:00,TS,16.4,-52.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23910,1900239N15318,1900,1,NA,NA,UNNAMED,8/29/1900 12:00,TS,16.5,-53.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23911,1900239N15318,1900,1,NA,NA,UNNAMED,8/29/1900 18:00,TS,16.6,-55.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23912,1900239N15318,1900,1,NA,NA,UNNAMED,8/30/1900 0:00,TS,16.8,-56.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23913,1900239N15318,1900,1,NA,NA,UNNAMED,8/30/1900 6:00,TS,16.9,-58.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23914,1900239N15318,1900,1,NA,NA,UNNAMED,8/30/1900 12:00,TS,17.0,-59.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23915,1900239N15318,1900,1,NA,CS,UNNAMED,8/30/1900 18:00,TS,17.0,-60.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23916,1900239N15318,1900,1,NA,CS,UNNAMED,8/31/1900 0:00,TS,17.1,-61.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23917,1900239N15318,1900,1,NA,CS,UNNAMED,8/31/1900 6:00,TS,17.2,-63.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23918,1900239N15318,1900,1,NA,CS,UNNAMED,8/31/1900 12:00,TS,17.3,-64.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23919,1900239N15318,1900,1,NA,CS,UNNAMED,8/31/1900 18:00,TS,17.4,-65.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23920,1900239N15318,1900,1,NA,CS,UNNAMED,9/1/1900 0:00,TS,17.5,-66.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23921,1900239N15318,1900,1,NA,CS,UNNAMED,9/1/1900 6:00,TS,17.6,-67.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23922,1900239N15318,1900,1,NA,CS,UNNAMED,9/1/1900 12:00,TS,17.7,-68.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23923,1900239N15318,1900,1,NA,CS,UNNAMED,9/1/1900 18:00,TS,18.0,-69.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23924,1900239N15318,1900,1,NA,NA,UNNAMED,9/2/1900 0:00,TS,18.3,-70.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23925,1900239N15318,1900,1,NA,NA,UNNAMED,9/2/1900 6:00,TS,18.7,-71.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23926,1900239N15318,1900,1,NA,NA,UNNAMED,9/2/1900 12:00,TS,19.0,-72.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23927,1900239N15318,1900,1,NA,CS,UNNAMED,9/2/1900 18:00,TS,19.3,-73.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23928,1900239N15318,1900,1,NA,CS,UNNAMED,9/3/1900 0:00,TS,19.5,-74.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23929,1900239N15318,1900,1,NA,CS,UNNAMED,9/3/1900 6:00,TS,19.7,-75.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179819,2005236N23285,2005,12,NA,GM,KATRINA,8/28/2005 6:00,TS,25.2,-86.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179820,2005236N23285,2005,12,NA,GM,KATRINA,8/28/2005 12:00,TS,25.7,-87.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179821,2005236N23285,2005,12,NA,GM,KATRINA,8/28/2005 18:00,TS,26.3,-88.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179822,2005236N23285,2005,12,NA,GM,KATRINA,8/29/2005 0:00,TS,27.2,-89.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179823,2005236N23285,2005,12,NA,GM,KATRINA,8/29/2005 6:00,TS,28.2,-89.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179824,2005236N23285,2005,12,NA,GM,KATRINA,8/29/2005 11:10,TS,29.3,-89.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179825,2005236N23285,2005,12,NA,GM,KATRINA,8/29/2005 12:00,TS,29.5,-89.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179826,2005236N23285,2005,12,NA,GM,KATRINA,8/29/2005 14:45,TS,30.2,-89.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179827,2005236N23285,2005,12,NA,NA,KATRINA,8/29/2005 18:00,TS,31.1,-89.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179828,2005236N23285,2005,12,NA,NA,KATRINA,8/30/2005 0:00,TS,32.6,-89.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179829,2005236N23285,2005,12,NA,NA,KATRINA,8/30/2005 6:00,TS,34.1,-88.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179830,2005236N23285,2005,12,NA,NA,KATRINA,8/30/2005 12:00,TS,35.6,-88.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
179831,2005236N23285,2005,12,NA,NA,KATRINA,8/30/2005 18:00,TS,37.0,-87.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180499,2005275N19274,2005,20,NA,CS,STAN,10/1/2005 12:00,TS,18.9,-85.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180500,2005275N19274,2005,20,NA,CS,STAN,10/1/2005 18:00,TS,19.1,-86.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180501,2005275N19274,2005,20,NA,CS,STAN,10/2/2005 0:00,TS,19.3,-86.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180502,2005275N19274,2005,20,NA,CS,STAN,10/2/2005 6:00,TS,19.5,-87.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180503,2005275N19274,2005,20,NA,CS,STAN,10/2/2005 10:00,TS,19.6,-87.5,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180504,2005275N19274,2005,20,NA,NA,STAN,10/2/2005 12:00,TS,19.8,-87.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180505,2005275N19274,2005,20,NA,NA,STAN,10/2/2005 18:00,TS,20.3,-88.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180506,2005275N19274,2005,20,NA,NA,STAN,10/3/2005 0:00,TS,20.5,-89.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180507,2005275N19274,2005,20,NA,GM,STAN,10/3/2005 6:00,TS,20.5,-91.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180508,2005275N19274,2005,20,NA,GM,STAN,10/3/2005 12:00,TS,20.3,-91.7,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180509,2005275N19274,2005,20,NA,GM,STAN,10/3/2005 18:00,TS,20.1,-92.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180510,2005275N19274,2005,20,NA,GM,STAN,10/4/2005 0:00,TS,19.8,-93.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180511,2005275N19274,2005,20,NA,GM,STAN,10/4/2005 6:00,TS,19.2,-94.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180512,2005275N19274,2005,20,NA,GM,STAN,10/4/2005 12:00,TS,18.6,-94.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180513,2005275N19274,2005,20,NA,NA,STAN,10/4/2005 18:00,TS,17.9,-95.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180514,2005275N19274,2005,20,NA,NA,STAN,10/5/2005 0:00,TS,17.2,-96.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
180515,2005275N19274,2005,20,NA,NA,STAN,10/5/2005 6:00,TS,16.9,-97.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [19]:
Filtered = SpecificStorms[['Serial_Num', 'Season', 'Name', 'ISO_time', 'Latitude', 'Longitude', 'Wind(WMO)']]
Filtered = Filtered.reset_index(drop=True)
Filtered

,Serial_Num,Season,Name,ISO_time,Latitude,Longitude,Wind(WMO)
0,1900239N15318,1900,UNNAMED,8/27/1900 0:00,15.0,-42.1,35
1,1900239N15318,1900,UNNAMED,8/27/1900 6:00,15.2,-43.4,35
2,1900239N15318,1900,UNNAMED,8/27/1900 12:00,15.3,-44.7,35
3,1900239N15318,1900,UNNAMED,8/27/1900 18:00,15.4,-45.6,35
4,1900239N15318,1900,UNNAMED,8/28/1900 0:00,15.6,-46.6,35
5,1900239N15318,1900,UNNAMED,8/28/1900 6:00,15.8,-47.9,35
6,1900239N15318,1900,UNNAMED,8/28/1900 12:00,16.0,-49.1,35
7,1900239N15318,1900,UNNAMED,8/28/1900 18:00,16.1,-50.3,35
8,1900239N15318,1900,UNNAMED,8/29/1900 0:00,16.3,-51.4,35
9,1900239N15318,1900,UNNAMED,8/29/1900 6:00,16.4,-52.4,35
10,1900239N15318,1900,UNNAMED,8/29/1900 12:00,16.5,-53.7,40
11,1900239N15318,1900,UNNAMED,8/29/1900 18:00,16.6,-55.1,40
12,1900239N15318,1900,UNNAMED,8/30/1900 0:00,16.8,-56.6,40
13,1900239N15318,1900,UNNAMED,8/30/1900 6:00,16.9,-58.0,40
14,1900239N15318,1900,UNNAMED,8/30/1900 12:00,17.0,-59.3,45
15,1900239N15318,1900,UNNAMED,8/30/1900 18:00,17.0,-60.6,45
16,1900239N15318,1900,UNNAMED,8/31/1900 0:00,17.1,-61.9,45
17,1900239N15318,1900,UNNAMED,8/31/1900 6:00,17.2,-63.3,45
18,1900239N15318,1900,UNNAMED,8/31/1900 12:00,17.3,-64.7,45
19,1900239N15318,1900,UNNAMED,8/31/1900 18:00,17.4,-65.6,45
20,1900239N15318,1900,UNNAMED,9/1/1900 0:00,17.5,-66.4,45
21,1900239N15318,1900,UNNAMED,9/1/1900 6:00,17.6,-67.4,45
22,1900239N15318,1900,UNNAMED,9/1/1900 12:00,17.7,-68.3,45
23,1900239N15318,1900,UNNAMED,9/1/1900 18:00,18.0,-69.2,40
24,1900239N15318,1900,UNNAMED,9/2/1900 0:00,18.3,-70.3,40
25,1900239N15318,1900,UNNAMED,9/2/1900 6:00,18.7,-71.3,35
26,1900239N15318,1900,UNNAMED,9/2/1900 12:00,19.0,-72.3,35
27,1900239N15318,1900,UNNAMED,9/2/1900 18:00,19.3,-73.2,35
28,1900239N15318,1900,UNNAMED,9/3/1900 0:00,19.5,-74.1,35
29,1900239N15318,1900,UNNAMED,9/3/1900 6:00,19.7,-75.0,35
...,...,...,...,...,...,...,...
408,2005236N23285,2005,KATRINA,8/28/2005 6:00,25.2,-86.7,125
409,2005236N23285,2005,KATRINA,8/28/2005 12:00,25.7,-87.7,145
410,2005236N23285,2005,KATRINA,8/28/2005 18:00,26.3,-88.6,150
411,2005236N23285,2005,KATRINA,8/29/2005 0:00,27.2,-89.2,140
412,2005236N23285,2005,KATRINA,8/29/2005 6:00,28.2,-89.6,125
413,2005236N23285,2005,KATRINA,8/29/2005 11:10,29.3,-89.6,110
414,2005236N23285,2005,KATRINA,8/29/2005 12:00,29.5,-89.6,110
415,2005236N23285,2005,KATRINA,8/29/2005 14:45,30.2,-89.6,105
416,2005236N23285,2005,KATRINA,8/29/2005 18:00,31.1,-89.6,80
417,2005236N23285,2005,KATRINA,8/30/2005 0:00,32.6,-89.1,50
418,2005236N23285,2005,KATRINA,8/30/2005 6:00,34.1,-88.6,40
419,2005236N23285,2005,KATRINA,8/30/2005 12:00,35.6,-88.0,30
420,2005236N23285,2005,KATRINA,8/30/2005 18:00,37.0,-87.0,30
421,2005275N19274,2005,STAN,10/1/2005 12:00,18.9,-85.6,25
422,2005275N19274,2005,STAN,10/1/2005 18:00,19.1,-86.2,30
423,2005275N19274,2005,STAN,10/2/2005 0:00,19.3,-86.7,30
424,2005275N19274,2005,STAN,10/2/2005 6:00,19.5,-87.2,40
425,2005275N19274,2005,STAN,10/2/2005 10:00,19.6,-87.5,35
426,2005275N19274,2005,STAN,10/2/2005 12:00,19.8,-87.9,35
427,2005275N19274,2005,STAN,10/2/2005 18:00,20.3,-88.8,35
428,2005275N19274,2005,STAN,10/3/2005 0:00,20.5,-89.8,30
429,2005275N19274,2005,STAN,10/3/2005 6:00,20.5,-91.0,35
430,2005275N19274,2005,STAN,10/3/2005 12:00,20.3,-91.7,40
431,2005275N19274,2005,STAN,10/3/2005 18:00,20.1,-92.2,50
432,2005275N19274,2005,STAN,10/4/2005 0:00,19.8,-93.2,55
433,2005275N19274,2005,STAN,10/4/2005 6:00,19.2,-94.1,65
434,2005275N19274,2005,STAN,10/4/2005 12:00,18.6,-94.9,70
435,2005275N19274,2005,STAN,10/4/2005 18:00,17.9,-95.6,45
436,2005275N19274,2005,STAN,10/5/2005 0:00,17.2,-96.4,30
437,2005275N19274,2005,STAN,10/5/2005 6:00,16.9,-97.0,25

In [20]:
Filtered['Deaths'] = 0
Filtered

,Serial_Num,Season,Name,ISO_time,Latitude,Longitude,Wind(WMO),Deaths
0,1900239N15318,1900,UNNAMED,8/27/1900 0:00,15.0,-42.1,35,0
1,1900239N15318,1900,UNNAMED,8/27/1900 6:00,15.2,-43.4,35,0
2,1900239N15318,1900,UNNAMED,8/27/1900 12:00,15.3,-44.7,35,0
3,1900239N15318,1900,UNNAMED,8/27/1900 18:00,15.4,-45.6,35,0
4,1900239N15318,1900,UNNAMED,8/28/1900 0:00,15.6,-46.6,35,0
5,1900239N15318,1900,UNNAMED,8/28/1900 6:00,15.8,-47.9,35,0
6,1900239N15318,1900,UNNAMED,8/28/1900 12:00,16.0,-49.1,35,0
7,1900239N15318,1900,UNNAMED,8/28/1900 18:00,16.1,-50.3,35,0
8,1900239N15318,1900,UNNAMED,8/29/1900 0:00,16.3,-51.4,35,0
9,1900239N15318,1900,UNNAMED,8/29/1900 6:00,16.4,-52.4,35,0
10,1900239N15318,1900,UNNAMED,8/29/1900 12:00,16.5,-53.7,40,0
11,1900239N15318,1900,UNNAMED,8/29/1900 18:00,16.6,-55.1,40,0
12,1900239N15318,1900,UNNAMED,8/30/1900 0:00,16.8,-56.6,40,0
13,1900239N15318,1900,UNNAMED,8/30/1900 6:00,16.9,-58.0,40,0
14,1900239N15318,1900,UNNAMED,8/30/1900 12:00,17.0,-59.3,45,0
15,1900239N15318,1900,UNNAMED,8/30/1900 18:00,17.0,-60.6,45,0
16,1900239N15318,1900,UNNAMED,8/31/1900 0:00,17.1,-61.9,45,0
17,1900239N15318,1900,UNNAMED,8/31/1900 6:00,17.2,-63.3,45,0
18,1900239N15318,1900,UNNAMED,8/31/1900 12:00,17.3,-64.7,45,0
19,1900239N15318,1900,UNNAMED,8/31/1900 18:00,17.4,-65.6,45,0
20,1900239N15318,1900,UNNAMED,9/1/1900 0:00,17.5,-66.4,45,0
21,1900239N15318,1900,UNNAMED,9/1/1900 6:00,17.6,-67.4,45,0
22,1900239N15318,1900,UNNAMED,9/1/1900 12:00,17.7,-68.3,45,0
23,1900239N15318,1900,UNNAMED,9/1/1900 18:00,18.0,-69.2,40,0
24,1900239N15318,1900,UNNAMED,9/2/1900 0:00,18.3,-70.3,40,0
25,1900239N15318,1900,UNNAMED,9/2/1900 6:00,18.7,-71.3,35,0
26,1900239N15318,1900,UNNAMED,9/2/1900 12:00,19.0,-72.3,35,0
27,1900239N15318,1900,UNNAMED,9/2/1900 18:00,19.3,-73.2,35,0
28,1900239N15318,1900,UNNAMED,9/3/1900 0:00,19.5,-74.1,35,0
29,1900239N15318,1900,UNNAMED,9/3/1900 6:00,19.7,-75.0,35,0
...,...,...,...,...,...,...,...,...
408,2005236N23285,2005,KATRINA,8/28/2005 6:00,25.2,-86.7,125,0
409,2005236N23285,2005,KATRINA,8/28/2005 12:00,25.7,-87.7,145,0
410,2005236N23285,2005,KATRINA,8/28/2005 18:00,26.3,-88.6,150,0
411,2005236N23285,2005,KATRINA,8/29/2005 0:00,27.2,-89.2,140,0
412,2005236N23285,2005,KATRINA,8/29/2005 6:00,28.2,-89.6,125,0
413,2005236N23285,2005,KATRINA,8/29/2005 11:10,29.3,-89.6,110,0
414,2005236N23285,2005,KATRINA,8/29/2005 12:00,29.5,-89.6,110,0
415,2005236N23285,2005,KATRINA,8/29/2005 14:45,30.2,-89.6,105,0
416,2005236N23285,2005,KATRINA,8/29/2005 18:00,31.1,-89.6,80,0
417,2005236N23285,2005,KATRINA,8/30/2005 0:00,32.6,-89.1,50,0
418,2005236N23285,2005,KATRINA,8/30/2005 6:00,34.1,-88.6,40,0
419,2005236N23285,2005,KATRINA,8/30/2005 12:00,35.6,-88.0,30,0
420,2005236N23285,2005,KATRINA,8/30/2005 18:00,37.0,-87.0,30,0
421,2005275N19274,2005,STAN,10/1/2005 12:00,18.9,-85.6,25,0
422,2005275N19274,2005,STAN,10/1/2005 18:00,19.1,-86.2,30,0
423,2005275N19274,2005,STAN,10/2/2005 0:00,19.3,-86.7,30,0
424,2005275N19274,2005,STAN,10/2/2005 6:00,19.5,-87.2,40,0
425,2005275N19274,2005,STAN,10/2/2005 10:00,19.6,-87.5,35,0
426,2005275N19274,2005,STAN,10/2/2005 12:00,19.8,-87.9,35,0
427,2005275N19274,2005,STAN,10/2/2005 18:00,20.3,-88.8,35,0
428,2005275N19274,2005,STAN,10/3/2005 0:00,20.5,-89.8,30,0
429,2005275N19274,2005,STAN,10/3/2005 6:00,20.5,-91.0,35,0
430,2005275N19274,2005,STAN,10/3/2005 12:00,20.3,-91.7,40,0
431,2005275N19274,2005,STAN,10/3/2005 18:00,20.1,-92.2,50,0
432,2005275N19274,2005,STAN,10/4/2005 0:00,19.8,-93.2,55,0
433,2005275N19274,2005,STAN,10/4/2005 6:00,19.2,-94.1,65,0
434,2005275N19274,2005,STAN,10/4/2005 12:00,18.6,-94.9,70,0
435,2005275N19274,2005,STAN,10/4/2005 18:00,17.9,-95.6,45,0
436,2005275N19274,2005,STAN,10/5/2005 0:00,17.2,-96.4,30,0
437,2005275N19274,2005,STAN,10/5/2005 6:00,16.9,-97.0,25,0

In [26]:
for x in range(len(Filtered)):
    if(Filtered['Serial_Num'][x] == '2005275N19274'):
        Filtered['Deaths'][x] = 1668
    elif(Filtered['Serial_Num'][x] == '2005236N23285'):
        Filtered['Deaths'][x] = 1836
    elif(Filtered['Serial_Num'][x] == '2004258N16300'):
        Filtered['Deaths'][x] = 3037
    elif(Filtered['Serial_Num'][x] == '1998295N12284'):
        Filtered['Deaths'][x] = 15000
    elif(Filtered['Serial_Num'][x] == '1994313N12278'):
        Filtered['Deaths'][x] = 1152
    elif(Filtered['Serial_Num'][x] == '1979238N12324'):
        Filtered['Deaths'][x] = 2068
    elif(Filtered['Serial_Num'][x] == '1974258N15295'):
        Filtered['Deaths'][x] = 8210
    elif(Filtered['Serial_Num'][x] == '1963270N08327'):
        Filtered['Deaths'][x] = 7193
    elif(Filtered['Serial_Num'][x] == '1900239N15318'):
        Filtered['Deaths'][x] = 10000
    elif(Filtered['Serial_Num'][x] == '1935292N12281'):
        Filtered['Deaths'][x] = 2150

Filtered

C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Jason-Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Serial_Num,Season,Name,ISO_time,Latitude,Longitude,Wind(WMO),Deaths
0,1900239N15318,1900,UNNAMED,8/27/1900 0:00,15.0,-42.1,35,10000
1,1900239N15318,1900,UNNAMED,8/27/1900 6:00,15.2,-43.4,35,10000
2,1900239N15318,1900,UNNAMED,8/27/1900 12:00,15.3,-44.7,35,10000
3,1900239N15318,1900,UNNAMED,8/27/1900 18:00,15.4,-45.6,35,10000
4,1900239N15318,1900,UNNAMED,8/28/1900 0:00,15.6,-46.6,35,10000
5,1900239N15318,1900,UNNAMED,8/28/1900 6:00,15.8,-47.9,35,10000
6,1900239N15318,1900,UNNAMED,8/28/1900 12:00,16.0,-49.1,35,10000
7,1900239N15318,1900,UNNAMED,8/28/1900 18:00,16.1,-50.3,35,10000
8,1900239N15318,1900,UNNAMED,8/29/1900 0:00,16.3,-51.4,35,10000
9,1900239N15318,1900,UNNAMED,8/29/1900 6:00,16.4,-52.4,35,10000
10,1900239N15318,1900,UNNAMED,8/29/1900 12:00,16.5,-53.7,40,10000
11,1900239N15318,1900,UNNAMED,8/29/1900 18:00,16.6,-55.1,40,10000
12,1900239N15318,1900,UNNAMED,8/30/1900 0:00,16.8,-56.6,40,10000
13,1900239N15318,1900,UNNAMED,8/30/1900 6:00,16.9,-58.0,40,10000
14,1900239N15318,1900,UNNAMED,8/30/1900 12:00,17.0,-59.3,45,10000
15,1900239N15318,1900,UNNAMED,8/30/1900 18:00,17.0,-60.6,45,10000
16,1900239N15318,1900,UNNAMED,8/31/1900 0:00,17.1,-61.9,45,10000
17,1900239N15318,1900,UNNAMED,8/31/1900 6:00,17.2,-63.3,45,10000
18,1900239N15318,1900,UNNAMED,8/31/1900 12:00,17.3,-64.7,45,10000
19,1900239N15318,1900,UNNAMED,8/31/1900 18:00,17.4,-65.6,45,10000
20,1900239N15318,1900,UNNAMED,9/1/1900 0:00,17.5,-66.4,45,10000
21,1900239N15318,1900,UNNAMED,9/1/1900 6:00,17.6,-67.4,45,10000
22,1900239N15318,1900,UNNAMED,9/1/1900 12:00,17.7,-68.3,45,10000
23,1900239N15318,1900,UNNAMED,9/1/1900 18:00,18.0,-69.2,40,10000
24,1900239N15318,1900,UNNAMED,9/2/1900 0:00,18.3,-70.3,40,10000
25,1900239N15318,1900,UNNAMED,9/2/1900 6:00,18.7,-71.3,35,10000
26,1900239N15318,1900,UNNAMED,9/2/1900 12:00,19.0,-72.3,35,10000
27,1900239N15318,1900,UNNAMED,9/2/1900 18:00,19.3,-73.2,35,10000
28,1900239N15318,1900,UNNAMED,9/3/1900 0:00,19.5,-74.1,35,10000
29,1900239N15318,1900,UNNAMED,9/3/1900 6:00,19.7,-75.0,35,10000
...,...,...,...,...,...,...,...,...
408,2005236N23285,2005,KATRINA,8/28/2005 6:00,25.2,-86.7,125,1836
409,2005236N23285,2005,KATRINA,8/28/2005 12:00,25.7,-87.7,145,1836
410,2005236N23285,2005,KATRINA,8/28/2005 18:00,26.3,-88.6,150,1836
411,2005236N23285,2005,KATRINA,8/29/2005 0:00,27.2,-89.2,140,1836
412,2005236N23285,2005,KATRINA,8/29/2005 6:00,28.2,-89.6,125,1836
413,2005236N23285,2005,KATRINA,8/29/2005 11:10,29.3,-89.6,110,1836
414,2005236N23285,2005,KATRINA,8/29/2005 12:00,29.5,-89.6,110,1836
415,2005236N23285,2005,KATRINA,8/29/2005 14:45,30.2,-89.6,105,1836
416,2005236N23285,2005,KATRINA,8/29/2005 18:00,31.1,-89.6,80,1836
417,2005236N23285,2005,KATRINA,8/30/2005 0:00,32.6,-89.1,50,1836
418,2005236N23285,2005,KATRINA,8/30/2005 6:00,34.1,-88.6,40,1836
419,2005236N23285,2005,KATRINA,8/30/2005 12:00,35.6,-88.0,30,1836
420,2005236N23285,2005,KATRINA,8/30/2005 18:00,37.0,-87.0,30,1836
421,2005275N19274,2005,STAN,10/1/2005 12:00,18.9,-85.6,25,1668
422,2005275N19274,2005,STAN,10/1/2005 18:00,19.1,-86.2,30,1668
423,2005275N19274,2005,STAN,10/2/2005 0:00,19.3,-86.7,30,1668
424,2005275N19274,2005,STAN,10/2/2005 6:00,19.5,-87.2,40,1668
425,2005275N19274,2005,STAN,10/2/2005 10:00,19.6,-87.5,35,1668
426,2005275N19274,2005,STAN,10/2/2005 12:00,19.8,-87.9,35,1668
427,2005275N19274,2005,STAN,10/2/2005 18:00,20.3,-88.8,35,1668
428,2005275N19274,2005,STAN,10/3/2005 0:00,20.5,-89.8,30,1668
429,2005275N19274,2005,STAN,10/3/2005 6:00,20.5,-91.0,35,1668
430,2005275N19274,2005,STAN,10/3/2005 12:00,20.3,-91.7,40,1668
431,2005275N19274,2005,STAN,10/3/2005 18:00,20.1,-92.2,50,1668
432,2005275N19274,2005,STAN,10/4/2005 0:00,19.8,-93.2,55,1668
433,2005275N19274,2005,STAN,10/4/2005 6:00,19.2,-94.1,65,1668
434,2005275N19274,2005,STAN,10/4/2005 12:00,18.6,-94.9,70,1668
435,2005275N19274,2005,STAN,10/4/2005 18:00,17.9,-95.6,45,1668
436,2005275N19274,2005,STAN,10/5/2005 0:00,17.2,-96.4,30,1668
437,2005275N19274,2005,STAN,10/5/2005 6:00,16.9,-97.0,25,1668

In [31]:
Filtered.rename(columns={'Wind(WMO)': 'Wind', 'Serial_Num': 'SerialNum', 'ISO_time': 'ISOTime'}, inplace=True)
Filtered

,SerialNum,Season,Name,ISOTime,Latitude,Longitude,Wind,Deaths
0,1900239N15318,1900,UNNAMED,8/27/1900 0:00,15.0,-42.1,35,10000
1,1900239N15318,1900,UNNAMED,8/27/1900 6:00,15.2,-43.4,35,10000
2,1900239N15318,1900,UNNAMED,8/27/1900 12:00,15.3,-44.7,35,10000
3,1900239N15318,1900,UNNAMED,8/27/1900 18:00,15.4,-45.6,35,10000
4,1900239N15318,1900,UNNAMED,8/28/1900 0:00,15.6,-46.6,35,10000
5,1900239N15318,1900,UNNAMED,8/28/1900 6:00,15.8,-47.9,35,10000
6,1900239N15318,1900,UNNAMED,8/28/1900 12:00,16.0,-49.1,35,10000
7,1900239N15318,1900,UNNAMED,8/28/1900 18:00,16.1,-50.3,35,10000
8,1900239N15318,1900,UNNAMED,8/29/1900 0:00,16.3,-51.4,35,10000
9,1900239N15318,1900,UNNAMED,8/29/1900 6:00,16.4,-52.4,35,10000
10,1900239N15318,1900,UNNAMED,8/29/1900 12:00,16.5,-53.7,40,10000
11,1900239N15318,1900,UNNAMED,8/29/1900 18:00,16.6,-55.1,40,10000
12,1900239N15318,1900,UNNAMED,8/30/1900 0:00,16.8,-56.6,40,10000
13,1900239N15318,1900,UNNAMED,8/30/1900 6:00,16.9,-58.0,40,10000
14,1900239N15318,1900,UNNAMED,8/30/1900 12:00,17.0,-59.3,45,10000
15,1900239N15318,1900,UNNAMED,8/30/1900 18:00,17.0,-60.6,45,10000
16,1900239N15318,1900,UNNAMED,8/31/1900 0:00,17.1,-61.9,45,10000
17,1900239N15318,1900,UNNAMED,8/31/1900 6:00,17.2,-63.3,45,10000
18,1900239N15318,1900,UNNAMED,8/31/1900 12:00,17.3,-64.7,45,10000
19,1900239N15318,1900,UNNAMED,8/31/1900 18:00,17.4,-65.6,45,10000
20,1900239N15318,1900,UNNAMED,9/1/1900 0:00,17.5,-66.4,45,10000
21,1900239N15318,1900,UNNAMED,9/1/1900 6:00,17.6,-67.4,45,10000
22,1900239N15318,1900,UNNAMED,9/1/1900 12:00,17.7,-68.3,45,10000
23,1900239N15318,1900,UNNAMED,9/1/1900 18:00,18.0,-69.2,40,10000
24,1900239N15318,1900,UNNAMED,9/2/1900 0:00,18.3,-70.3,40,10000
25,1900239N15318,1900,UNNAMED,9/2/1900 6:00,18.7,-71.3,35,10000
26,1900239N15318,1900,UNNAMED,9/2/1900 12:00,19.0,-72.3,35,10000
27,1900239N15318,1900,UNNAMED,9/2/1900 18:00,19.3,-73.2,35,10000
28,1900239N15318,1900,UNNAMED,9/3/1900 0:00,19.5,-74.1,35,10000
29,1900239N15318,1900,UNNAMED,9/3/1900 6:00,19.7,-75.0,35,10000
...,...,...,...,...,...,...,...,...
408,2005236N23285,2005,KATRINA,8/28/2005 6:00,25.2,-86.7,125,1836
409,2005236N23285,2005,KATRINA,8/28/2005 12:00,25.7,-87.7,145,1836
410,2005236N23285,2005,KATRINA,8/28/2005 18:00,26.3,-88.6,150,1836
411,2005236N23285,2005,KATRINA,8/29/2005 0:00,27.2,-89.2,140,1836
412,2005236N23285,2005,KATRINA,8/29/2005 6:00,28.2,-89.6,125,1836
413,2005236N23285,2005,KATRINA,8/29/2005 11:10,29.3,-89.6,110,1836
414,2005236N23285,2005,KATRINA,8/29/2005 12:00,29.5,-89.6,110,1836
415,2005236N23285,2005,KATRINA,8/29/2005 14:45,30.2,-89.6,105,1836
416,2005236N23285,2005,KATRINA,8/29/2005 18:00,31.1,-89.6,80,1836
417,2005236N23285,2005,KATRINA,8/30/2005 0:00,32.6,-89.1,50,1836
418,2005236N23285,2005,KATRINA,8/30/2005 6:00,34.1,-88.6,40,1836
419,2005236N23285,2005,KATRINA,8/30/2005 12:00,35.6,-88.0,30,1836
420,2005236N23285,2005,KATRINA,8/30/2005 18:00,37.0,-87.0,30,1836
421,2005275N19274,2005,STAN,10/1/2005 12:00,18.9,-85.6,25,1668
422,2005275N19274,2005,STAN,10/1/2005 18:00,19.1,-86.2,30,1668
423,2005275N19274,2005,STAN,10/2/2005 0:00,19.3,-86.7,30,1668
424,2005275N19274,2005,STAN,10/2/2005 6:00,19.5,-87.2,40,1668
425,2005275N19274,2005,STAN,10/2/2005 10:00,19.6,-87.5,35,1668
426,2005275N19274,2005,STAN,10/2/2005 12:00,19.8,-87.9,35,1668
427,2005275N19274,2005,STAN,10/2/2005 18:00,20.3,-88.8,35,1668
428,2005275N19274,2005,STAN,10/3/2005 0:00,20.5,-89.8,30,1668
429,2005275N19274,2005,STAN,10/3/2005 6:00,20.5,-91.0,35,1668
430,2005275N19274,2005,STAN,10/3/2005 12:00,20.3,-91.7,40,1668
431,2005275N19274,2005,STAN,10/3/2005 18:00,20.1,-92.2,50,1668
432,2005275N19274,2005,STAN,10/4/2005 0:00,19.8,-93.2,55,1668
433,2005275N19274,2005,STAN,10/4/2005 6:00,19.2,-94.1,65,1668
434,2005275N19274,2005,STAN,10/4/2005 12:00,18.6,-94.9,70,1668
435,2005275N19274,2005,STAN,10/4/2005 18:00,17.9,-95.6,45,1668
436,2005275N19274,2005,STAN,10/5/2005 0:00,17.2,-96.4,30,1668
437,2005275N19274,2005,STAN,10/5/2005 6:00,16.9,-97.0,25,1668

In [32]:
Filtered.to_csv (r'FilteredStorms.csv', index = None, header=True)