In [1]:
import pandas

In [2]:
data = pandas.read_csv("storms.csv", low_memory=False)
data

,Serial_Num,Season,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,...,jtwc_??_wrad34_rad3,jtwc_??_wrad34_rad4,jtwc_??_wrad50_rad1,jtwc_??_wrad50_rad2,jtwc_??_wrad50_rad3,jtwc_??_wrad50_rad4,jtwc_??_wrad64_rad1,jtwc_??_wrad64_rad2,jtwc_??_wrad64_rad3,jtwc_??_wrad64_rad4
0,1842298N11080,1842,1,NI,BB,NOT NAMED,1842-10-25 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,1842298N11080,1842,1,NI,BB,NOT NAMED,1842-10-25 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-25 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
5,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
6,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-26 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
7,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
8,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-27 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
11,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
12,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
14,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-28 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
15,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
17,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
18,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-29 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
20,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
21,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
22,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-30 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
24,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
25,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
26,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-10-31 18:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
27,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 00:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
28,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 06:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
29,1842298N11080,1842,1,NI,AS,NOT NAMED,1842-11-01 12:00:00,NR,-999.00,-999.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344776,2016040S17154,2016,2,SP,EA,TATIANA,2/10/2016 18:00,NR,-16.48,156.82,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344777,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 0:00,NR,-16.75,157.38,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344778,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 6:00,NR,-16.92,157.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344779,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 12:00,NR,-16.80,158.26,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344780,2016040S17154,2016,2,SP,EA,TATIANA,2/11/2016 18:00,NR,-17.08,158.75,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344781,2016040S17154,2016,2,SP,EA,TATIANA,2/12/2016 0:00,NR,-17.23,159.38,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344782,2016040S17154,2016,2,SP,EA,TATIANA,2/12/2016 6:00,NR,-18.15,159.80,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344783,2016040S17154,2016,2,SP,MM,TATIANA,2/12/2016 12:00,NR,-18.95,160.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344784,2016040S17154,2016,2,SP,MM,TATIANA,2/12/2016 18:00,NR,-20.01,160.21,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344785,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 0:00,NR,-21.00,160.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344786,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 6:00,NR,-22.64,160.27,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344787,2016040S17154,2016,2,SP,MM,TATIANA,2/13/2016 12:00,NR,-24.09,160.29,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344788,2016040S17154,2016,2,SP,EA,TATIANA,2/13/2016 18:00,NR,-25.32,159.71,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344789,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 0:00,NR,-26.02,159.20,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344790,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 6:00,NR,-26.00,159.00,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344791,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 12:00,NR,-25.60,158.65,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344792,2016040S17154,2016,2,SP,EA,TATIANA,2/14/2016 18:00,NR,-25.20,158.30,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344793,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 0:00,NR,-24.80,158.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344794,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 6:00,NR,-24.40,158.70,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344795,2016040S17154,2016,2,SP,EA,TATIANA,2/15/2016 12:00,NR,-24.20,158.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344796,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 0:00,NR,-15.50,137.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344797,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 6:00,NR,-15.80,137.50,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344798,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 12:00,NR,-15.90,136.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344799,2016074S16137,2016,3,SP,EA,NONAME,3/14/2016 18:00,NR,-15.80,137.20,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344800,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 0:00,NR,-15.80,137.80,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344801,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 6:00,NR,-15.50,137.90,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344802,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 12:00,NR,-15.60,138.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344803,2016074S16137,2016,3,SP,EA,NONAME,3/15/2016 18:00,NR,-16.00,139.40,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344804,2016074S16137,2016,3,SP,EA,NONAME,3/16/2016 0:00,NR,-16.40,140.30,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
344805,2016074S16137,2016,3,SP,EA,NONAME,3/16/2016 6:00,NR,-16.55,141.10,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [3]:
data['Nature'].value_counts()

 TS    200117
 NR    124817
 ET     15378
 DS      3061
 SS      1291
 MX       142
Name: Nature, dtype: int64

In [4]:
TS = data.loc[data['Nature'] == " TS"]
TS = TS.reset_index(drop=True)
TS

,Serial_Num,Season,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,...,jtwc_??_wrad34_rad3,jtwc_??_wrad34_rad4,jtwc_??_wrad50_rad1,jtwc_??_wrad50_rad2,jtwc_??_wrad50_rad3,jtwc_??_wrad50_rad4,jtwc_??_wrad64_rad1,jtwc_??_wrad64_rad2,jtwc_??_wrad64_rad3,jtwc_??_wrad64_rad4
0,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-23 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-23 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
5,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-24 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
6,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 00:00:00,TS,28.0,-94.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
7,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 06:00:00,TS,28.0,-95.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
8,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 12:00:00,TS,28.0,-96.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
9,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 18:00:00,TS,28.1,-96.5,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
10,1851175N26270,1851,1,NA,GM,UNNAMED,1851-06-25 21:00:00,TS,28.2,-96.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
11,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 00:00:00,TS,28.2,-97.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
12,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 06:00:00,TS,28.3,-97.6,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
13,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 12:00:00,TS,28.4,-98.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
14,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-26 18:00:00,TS,28.6,-98.9,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
15,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 00:00:00,TS,29.0,-99.4,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
16,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 06:00:00,TS,29.5,-99.8,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
17,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 12:00:00,TS,30.0,-100.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
18,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-27 18:00:00,TS,30.5,-100.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
19,1851175N26270,1851,1,NA,NA,UNNAMED,1851-06-28 00:00:00,TS,31.0,-100.2,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
20,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-29 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
21,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-29 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
22,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-30 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
23,1851181N19275,1851,2,NA,CS,NOT NAMED,1851-06-30 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
24,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-06-30 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
25,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-06-30 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
26,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-07-01 00:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
27,1851181N19275,1851,2,NA,NA,NOT NAMED,1851-07-01 06:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
28,1851181N19275,1851,2,NA,GM,NOT NAMED,1851-07-01 12:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
29,1851181N19275,1851,2,NA,GM,NOT NAMED,1851-07-01 18:00:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200087,2015344N07145,2015,28,WP,MM,MELOR,12/13/2015 12:00,TS,12.4,128.1,...,80,125,70,60,60,80,35,30,30,35
200088,2015344N07145,2015,28,WP,MM,MELOR,12/13/2015 18:00,TS,12.5,126.9,...,90,135,80,60,60,80,35,30,30,35
200089,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 0:00,TS,12.5,125.8,...,75,110,80,60,60,80,35,30,30,35
200090,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 6:00,TS,12.6,124.6,...,75,110,80,60,60,80,35,30,30,35
200091,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 12:00,TS,12.8,123.5,...,75,110,80,60,60,80,35,30,30,35
200092,2015344N07145,2015,28,WP,MM,MELOR,12/14/2015 18:00,TS,12.9,122.6,...,75,110,65,65,65,65,25,25,25,25
200093,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 0:00,TS,13.0,121.8,...,75,110,65,65,65,65,25,25,25,25
200094,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 6:00,TS,13.2,121.2,...,75,110,65,65,65,65,20,20,20,20
200095,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 12:00,TS,13.4,120.6,...,75,110,65,65,65,65,20,20,20,20
200096,2015344N07145,2015,28,WP,MM,MELOR,12/15/2015 18:00,TS,13.7,120.1,...,90,110,65,50,50,65,-1,-1,-1,-1
200097,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 0:00,TS,14.1,120.1,...,75,95,-1,-1,-1,-1,-1,-1,-1,-1
200098,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 6:00,TS,14.1,120.3,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200099,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 12:00,TS,13.7,120.3,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200100,2015344N07145,2015,28,WP,MM,MELOR,12/16/2015 18:00,TS,13.1,120.3,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200101,2015344N07145,2015,28,WP,MM,MELOR,12/17/2015 0:00,TS,12.5,120.1,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200102,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/14/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200103,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/14/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200104,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/16/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200105,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/16/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200106,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 0:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200107,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 6:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200108,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 12:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200109,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/17/2015 18:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200110,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 0:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200111,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 6:00,TS,-999.0,-999.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
200112,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 12:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200113,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/18/2015 18:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200114,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 0:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200115,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 6:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
200116,2015348N04146,2015,29,WP,MM,TWENTYNINE,12/19/2015 12:00,TS,-999.0,-999.0,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [5]:
Filtered = TS[['Serial_Num', 'Season', 'Name', 'ISO_time', 'Latitude', 'Longitude', 'Wind(WMO)']]
Filtered = Filtered.reset_index(drop=True)
Filtered

,Serial_Num,Season,Name,ISO_time,Latitude,Longitude,Wind(WMO)
0,1851175N26270,1851,UNNAMED,1851-06-23 12:00:00,-999.0,-999.0,-999
1,1851175N26270,1851,UNNAMED,1851-06-23 18:00:00,-999.0,-999.0,-999
2,1851175N26270,1851,UNNAMED,1851-06-24 00:00:00,-999.0,-999.0,-999
3,1851175N26270,1851,UNNAMED,1851-06-24 06:00:00,-999.0,-999.0,-999
4,1851175N26270,1851,UNNAMED,1851-06-24 12:00:00,-999.0,-999.0,-999
5,1851175N26270,1851,UNNAMED,1851-06-24 18:00:00,-999.0,-999.0,-999
6,1851175N26270,1851,UNNAMED,1851-06-25 00:00:00,28.0,-94.8,80
7,1851175N26270,1851,UNNAMED,1851-06-25 06:00:00,28.0,-95.4,80
8,1851175N26270,1851,UNNAMED,1851-06-25 12:00:00,28.0,-96.0,80
9,1851175N26270,1851,UNNAMED,1851-06-25 18:00:00,28.1,-96.5,80
10,1851175N26270,1851,UNNAMED,1851-06-25 21:00:00,28.2,-96.8,80
11,1851175N26270,1851,UNNAMED,1851-06-26 00:00:00,28.2,-97.0,70
12,1851175N26270,1851,UNNAMED,1851-06-26 06:00:00,28.3,-97.6,60
13,1851175N26270,1851,UNNAMED,1851-06-26 12:00:00,28.4,-98.3,60
14,1851175N26270,1851,UNNAMED,1851-06-26 18:00:00,28.6,-98.9,50
15,1851175N26270,1851,UNNAMED,1851-06-27 00:00:00,29.0,-99.4,50
16,1851175N26270,1851,UNNAMED,1851-06-27 06:00:00,29.5,-99.8,40
17,1851175N26270,1851,UNNAMED,1851-06-27 12:00:00,30.0,-100.0,40
18,1851175N26270,1851,UNNAMED,1851-06-27 18:00:00,30.5,-100.1,40
19,1851175N26270,1851,UNNAMED,1851-06-28 00:00:00,31.0,-100.2,40
20,1851181N19275,1851,NOT NAMED,1851-06-29 12:00:00,-999.0,-999.0,-999
21,1851181N19275,1851,NOT NAMED,1851-06-29 18:00:00,-999.0,-999.0,-999
22,1851181N19275,1851,NOT NAMED,1851-06-30 00:00:00,-999.0,-999.0,-999
23,1851181N19275,1851,NOT NAMED,1851-06-30 06:00:00,-999.0,-999.0,-999
24,1851181N19275,1851,NOT NAMED,1851-06-30 12:00:00,-999.0,-999.0,-999
25,1851181N19275,1851,NOT NAMED,1851-06-30 18:00:00,-999.0,-999.0,-999
26,1851181N19275,1851,NOT NAMED,1851-07-01 00:00:00,-999.0,-999.0,-999
27,1851181N19275,1851,NOT NAMED,1851-07-01 06:00:00,-999.0,-999.0,-999
28,1851181N19275,1851,NOT NAMED,1851-07-01 12:00:00,-999.0,-999.0,-999
29,1851181N19275,1851,NOT NAMED,1851-07-01 18:00:00,-999.0,-999.0,-999
...,...,...,...,...,...,...,...
200087,2015344N07145,2015,MELOR,12/13/2015 12:00,12.4,128.1,85
200088,2015344N07145,2015,MELOR,12/13/2015 18:00,12.5,126.9,85
200089,2015344N07145,2015,MELOR,12/14/2015 0:00,12.5,125.8,95
200090,2015344N07145,2015,MELOR,12/14/2015 6:00,12.6,124.6,95
200091,2015344N07145,2015,MELOR,12/14/2015 12:00,12.8,123.5,80
200092,2015344N07145,2015,MELOR,12/14/2015 18:00,12.9,122.6,80
200093,2015344N07145,2015,MELOR,12/15/2015 0:00,13.0,121.8,85
200094,2015344N07145,2015,MELOR,12/15/2015 6:00,13.2,121.2,85
200095,2015344N07145,2015,MELOR,12/15/2015 12:00,13.4,120.6,80
200096,2015344N07145,2015,MELOR,12/15/2015 18:00,13.7,120.1,70
200097,2015344N07145,2015,MELOR,12/16/2015 0:00,14.1,120.1,65
200098,2015344N07145,2015,MELOR,12/16/2015 6:00,14.1,120.3,50
200099,2015344N07145,2015,MELOR,12/16/2015 12:00,13.7,120.3,45
200100,2015344N07145,2015,MELOR,12/16/2015 18:00,13.1,120.3,35
200101,2015344N07145,2015,MELOR,12/17/2015 0:00,12.5,120.1,0
200102,2015348N04146,2015,TWENTYNINE,12/14/2015 12:00,-999.0,-999.0,-999
200103,2015348N04146,2015,TWENTYNINE,12/14/2015 18:00,-999.0,-999.0,-999
200104,2015348N04146,2015,TWENTYNINE,12/16/2015 12:00,-999.0,-999.0,-999
200105,2015348N04146,2015,TWENTYNINE,12/16/2015 18:00,-999.0,-999.0,-999
200106,2015348N04146,2015,TWENTYNINE,12/17/2015 0:00,-999.0,-999.0,-999
200107,2015348N04146,2015,TWENTYNINE,12/17/2015 6:00,-999.0,-999.0,-999
200108,2015348N04146,2015,TWENTYNINE,12/17/2015 12:00,-999.0,-999.0,-999
200109,2015348N04146,2015,TWENTYNINE,12/17/2015 18:00,-999.0,-999.0,-999
200110,2015348N04146,2015,TWENTYNINE,12/18/2015 0:00,-999.0,-999.0,-999
200111,2015348N04146,2015,TWENTYNINE,12/18/2015 6:00,-999.0,-999.0,-999
200112,2015348N04146,2015,TWENTYNINE,12/18/2015 12:00,-999.0,-999.0,-999
200113,2015348N04146,2015,TWENTYNINE,12/18/2015 18:00,-999.0,-999.0,-999
200114,2015348N04146,2015,TWENTYNINE,12/19/2015 0:00,-999.0,-999.0,-999
200115,2015348N04146,2015,TWENTYNINE,12/19/2015 6:00,-999.0,-999.0,-999
200116,2015348N04146,2015,TWENTYNINE,12/19/2015 12:00,-999.0,-999.0,-999

In [6]:
Filtered.rename(columns={'Wind(WMO)': 'Wind', 'Serial_Num': 'SerialNum', 'ISO_time': 'ISOTime'}, inplace=True)
Filtered

,SerialNum,Season,Name,ISOTime,Latitude,Longitude,Wind
0,1851175N26270,1851,UNNAMED,1851-06-23 12:00:00,-999.0,-999.0,-999
1,1851175N26270,1851,UNNAMED,1851-06-23 18:00:00,-999.0,-999.0,-999
2,1851175N26270,1851,UNNAMED,1851-06-24 00:00:00,-999.0,-999.0,-999
3,1851175N26270,1851,UNNAMED,1851-06-24 06:00:00,-999.0,-999.0,-999
4,1851175N26270,1851,UNNAMED,1851-06-24 12:00:00,-999.0,-999.0,-999
5,1851175N26270,1851,UNNAMED,1851-06-24 18:00:00,-999.0,-999.0,-999
6,1851175N26270,1851,UNNAMED,1851-06-25 00:00:00,28.0,-94.8,80
7,1851175N26270,1851,UNNAMED,1851-06-25 06:00:00,28.0,-95.4,80
8,1851175N26270,1851,UNNAMED,1851-06-25 12:00:00,28.0,-96.0,80
9,1851175N26270,1851,UNNAMED,1851-06-25 18:00:00,28.1,-96.5,80
10,1851175N26270,1851,UNNAMED,1851-06-25 21:00:00,28.2,-96.8,80
11,1851175N26270,1851,UNNAMED,1851-06-26 00:00:00,28.2,-97.0,70
12,1851175N26270,1851,UNNAMED,1851-06-26 06:00:00,28.3,-97.6,60
13,1851175N26270,1851,UNNAMED,1851-06-26 12:00:00,28.4,-98.3,60
14,1851175N26270,1851,UNNAMED,1851-06-26 18:00:00,28.6,-98.9,50
15,1851175N26270,1851,UNNAMED,1851-06-27 00:00:00,29.0,-99.4,50
16,1851175N26270,1851,UNNAMED,1851-06-27 06:00:00,29.5,-99.8,40
17,1851175N26270,1851,UNNAMED,1851-06-27 12:00:00,30.0,-100.0,40
18,1851175N26270,1851,UNNAMED,1851-06-27 18:00:00,30.5,-100.1,40
19,1851175N26270,1851,UNNAMED,1851-06-28 00:00:00,31.0,-100.2,40
20,1851181N19275,1851,NOT NAMED,1851-06-29 12:00:00,-999.0,-999.0,-999
21,1851181N19275,1851,NOT NAMED,1851-06-29 18:00:00,-999.0,-999.0,-999
22,1851181N19275,1851,NOT NAMED,1851-06-30 00:00:00,-999.0,-999.0,-999
23,1851181N19275,1851,NOT NAMED,1851-06-30 06:00:00,-999.0,-999.0,-999
24,1851181N19275,1851,NOT NAMED,1851-06-30 12:00:00,-999.0,-999.0,-999
25,1851181N19275,1851,NOT NAMED,1851-06-30 18:00:00,-999.0,-999.0,-999
26,1851181N19275,1851,NOT NAMED,1851-07-01 00:00:00,-999.0,-999.0,-999
27,1851181N19275,1851,NOT NAMED,1851-07-01 06:00:00,-999.0,-999.0,-999
28,1851181N19275,1851,NOT NAMED,1851-07-01 12:00:00,-999.0,-999.0,-999
29,1851181N19275,1851,NOT NAMED,1851-07-01 18:00:00,-999.0,-999.0,-999
...,...,...,...,...,...,...,...
200087,2015344N07145,2015,MELOR,12/13/2015 12:00,12.4,128.1,85
200088,2015344N07145,2015,MELOR,12/13/2015 18:00,12.5,126.9,85
200089,2015344N07145,2015,MELOR,12/14/2015 0:00,12.5,125.8,95
200090,2015344N07145,2015,MELOR,12/14/2015 6:00,12.6,124.6,95
200091,2015344N07145,2015,MELOR,12/14/2015 12:00,12.8,123.5,80
200092,2015344N07145,2015,MELOR,12/14/2015 18:00,12.9,122.6,80
200093,2015344N07145,2015,MELOR,12/15/2015 0:00,13.0,121.8,85
200094,2015344N07145,2015,MELOR,12/15/2015 6:00,13.2,121.2,85
200095,2015344N07145,2015,MELOR,12/15/2015 12:00,13.4,120.6,80
200096,2015344N07145,2015,MELOR,12/15/2015 18:00,13.7,120.1,70
200097,2015344N07145,2015,MELOR,12/16/2015 0:00,14.1,120.1,65
200098,2015344N07145,2015,MELOR,12/16/2015 6:00,14.1,120.3,50
200099,2015344N07145,2015,MELOR,12/16/2015 12:00,13.7,120.3,45
200100,2015344N07145,2015,MELOR,12/16/2015 18:00,13.1,120.3,35
200101,2015344N07145,2015,MELOR,12/17/2015 0:00,12.5,120.1,0
200102,2015348N04146,2015,TWENTYNINE,12/14/2015 12:00,-999.0,-999.0,-999
200103,2015348N04146,2015,TWENTYNINE,12/14/2015 18:00,-999.0,-999.0,-999
200104,2015348N04146,2015,TWENTYNINE,12/16/2015 12:00,-999.0,-999.0,-999
200105,2015348N04146,2015,TWENTYNINE,12/16/2015 18:00,-999.0,-999.0,-999
200106,2015348N04146,2015,TWENTYNINE,12/17/2015 0:00,-999.0,-999.0,-999
200107,2015348N04146,2015,TWENTYNINE,12/17/2015 6:00,-999.0,-999.0,-999
200108,2015348N04146,2015,TWENTYNINE,12/17/2015 12:00,-999.0,-999.0,-999
200109,2015348N04146,2015,TWENTYNINE,12/17/2015 18:00,-999.0,-999.0,-999
200110,2015348N04146,2015,TWENTYNINE,12/18/2015 0:00,-999.0,-999.0,-999
200111,2015348N04146,2015,TWENTYNINE,12/18/2015 6:00,-999.0,-999.0,-999
200112,2015348N04146,2015,TWENTYNINE,12/18/2015 12:00,-999.0,-999.0,-999
200113,2015348N04146,2015,TWENTYNINE,12/18/2015 18:00,-999.0,-999.0,-999
200114,2015348N04146,2015,TWENTYNINE,12/19/2015 0:00,-999.0,-999.0,-999
200115,2015348N04146,2015,TWENTYNINE,12/19/2015 6:00,-999.0,-999.0,-999
200116,2015348N04146,2015,TWENTYNINE,12/19/2015 12:00,-999.0,-999.0,-999

In [7]:
deaths = pandas.read_csv("casualties.csv", low_memory=False)
deaths

,SerialNum,Name,Deaths,Damages,EvacuationDate,FirstHurricaneWarning,EvacuationType,NumEntries
0,2005236N23285,KATRINA,1200,108000,8/28/2005,8/25/2005,Mandatory,32.0
1,2012296N14283,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
2,2008238N14293,GUSTAV,112,4618,NaN,NaN,NaN,NaN
3,2008241N19303,HANNA,500,160,NaN,NaN,NaN,NaN
4,2008245N17323,IKE,103,29520,NaN,NaN,Mandatory,57.0
5,2007244N12303,FELIX,130,0,NaN,NaN,NaN,NaN
6,2007297N18300,NOEL,163,0,NaN,NaN,NaN,NaN
7,2005275N19274,STAN,80,0,NaN,NaN,NaN,NaN
8,2004247N10332,IVAN,92,18820,NaN,NaN,NaN,NaN
9,2004258N16300,JEANNE,3000,7660,NaN,NaN,Voluntary,66.0
10,1998259N10335,GEORGES,602,2765,NaN,NaN,NaN,NaN
11,1998295N12284,MITCH,9086,40,10/25/1998,NaN,Voluntary,54.0
12,1994313N12278,GORDON,1145,400,NaN,NaN,NaN,NaN
13,1993217N10320,BRET,184,0,NaN,NaN,NaN,NaN
14,1992230N11325,ANDREW,26,26500,NaN,NaN,Both,52.0
15,1991228N26286,BOB,17,1500,NaN,NaN,NaN,NaN
16,1990216N13281,DIANA,96,0,NaN,NaN,NaN,NaN
17,1994181N22276,ALBERTO,30,500,NaN,NaN,NaN,NaN
18,1995212N22287,ERIN,6,700,NaN,NaN,NaN,NaN
19,1995271N19273,OPAL,59,5142,NaN,NaN,NaN,NaN
20,1996187N10326,BERTHA,12,270,NaN,NaN,NaN,NaN
21,1996237N14339,FRAN,34,4160,NaN,NaN,NaN,NaN
22,1996279N23264,JOSEPHINE,0,130,NaN,NaN,NaN,NaN
23,1997198N27267,DANNY,5,100,NaN,NaN,NaN,NaN
24,1998232N15312,BONNIE,3,720,NaN,NaN,NaN,NaN
25,1998244N22267,EARL,3,700,NaN,NaN,NaN,NaN
26,1998252N26266,FRANCES,1,500,NaN,NaN,NaN,NaN
27,1999236N22292,DENNIS,4,157,NaN,NaN,NaN,NaN
28,1999251N15314,FLOYD,57,6900,NaN,NaN,NaN,NaN
29,1999286N16278,IRENE,0,800,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
70,1976219N26287,BELLE,0,100,NaN,NaN,NaN,NaN
71,1979197N13314,CLAUDETTE,2,400,NaN,NaN,NaN,NaN
72,1979238N12324,DAVID,2068,320,NaN,NaN,NaN,NaN
73,1979241N11335,FREDERIC,12,2300,NaN,NaN,NaN,NaN
74,1900239N15318,GALVESTON,12000,30,NaN,NaN,None,63.0
75,1903252N21288,UNNAMED,188,0,NaN,NaN,NaN,NaN
76,1906263N12283,UNNAMED,134,0,NaN,NaN,NaN,NaN
77,1906281N11284,UNNAMED,193,0,NaN,NaN,NaN,NaN
78,1909264N21088,UNNAMED,1500,0,NaN,NaN,NaN,NaN
79,1909280N11284,UNNAMED,130,0,NaN,NaN,NaN,NaN
80,1919245N33287,UNNAMED,600,22,NaN,NaN,NaN,NaN
81,1926287N12279,UNNAMED,709,0,NaN,NaN,NaN,NaN
82,1928250N14343,UNNAMED,3411,0,NaN,NaN,NaN,NaN
83,1932304N15305,UNNAMED,3107,0,NaN,NaN,NaN,NaN
84,1934156N17273,UNNAMED,3000,3,NaN,NaN,NaN,NaN
85,1935292N13279,UNNAMED,2150,0,NaN,NaN,NaN,NaN
86,1938253N13314,UNNAMED,682,306,NaN,NaN,NaN,NaN
87,1952295N11282,FOX,600,0,NaN,NaN,NaN,NaN
88,1954278N12302,HAZEL,1000,281,NaN,NaN,NaN,NaN
89,1955265N13307,JANET,681,0,NaN,NaN,NaN,NaN
90,1957176N21267,AUDREY,416,150,NaN,NaN,NaN,NaN
91,1963270N08327,FLORA,8000,0,NaN,NaN,Voluntary,65.0
92,1966265N10325,INEZ,1000,5,NaN,NaN,NaN,NaN
93,1899215N18130,UNNAMED,3369,0,NaN,NaN,NaN,NaN
94,1893228N32300,UNNAMED,2500,0,NaN,NaN,NaN,NaN
95,1893271N16278,UNNAMED,2000,0,NaN,NaN,NaN,NaN
96,1969226N18280,CAMILLE,259,1421,NaN,NaN,NaN,NaN
97,1964234N13316,CLEO,217,128,NaN,NaN,NaN,NaN
98,1955219N16319,DIANE,200,832,NaN,NaN,NaN,NaN
99,1961301N12279,HATTIE,275,0,NaN,NaN,NaN,NaN

In [8]:
merged = pandas.merge(Filtered, deaths, on=['SerialNum'])
merged

,SerialNum,Season,Name_x,ISOTime,Latitude,Longitude,Wind,Name_y,Deaths,Damages,EvacuationDate,FirstHurricaneWarning,EvacuationType,NumEntries
0,1893228N32300,1893,UNNAMED,1893-08-15 12:00:00,32.2,-60.4,35,UNNAMED,2500,0,NaN,NaN,NaN,NaN
1,1893228N32300,1893,UNNAMED,1893-08-15 18:00:00,33.1,-62.1,40,UNNAMED,2500,0,NaN,NaN,NaN,NaN
2,1893228N32300,1893,UNNAMED,1893-08-16 00:00:00,34.2,-64.0,45,UNNAMED,2500,0,NaN,NaN,NaN,NaN
3,1893228N32300,1893,UNNAMED,1893-08-16 06:00:00,35.5,-66.1,55,UNNAMED,2500,0,NaN,NaN,NaN,NaN
4,1893228N32300,1893,UNNAMED,1893-08-16 12:00:00,37.0,-67.0,60,UNNAMED,2500,0,NaN,NaN,NaN,NaN
5,1893228N32300,1893,UNNAMED,1893-08-16 18:00:00,38.4,-66.1,70,UNNAMED,2500,0,NaN,NaN,NaN,NaN
6,1893228N32300,1893,UNNAMED,1893-08-17 00:00:00,40.2,-64.7,80,UNNAMED,2500,0,NaN,NaN,NaN,NaN
7,1893228N32300,1893,UNNAMED,1893-08-17 06:00:00,41.9,-62.7,85,UNNAMED,2500,0,NaN,NaN,NaN,NaN
8,1893228N32300,1893,UNNAMED,1893-08-17 12:00:00,43.4,-60.8,85,UNNAMED,2500,0,NaN,NaN,NaN,NaN
9,1893228N32300,1893,UNNAMED,1893-08-17 18:00:00,44.8,-58.8,85,UNNAMED,2500,0,NaN,NaN,NaN,NaN
10,1893228N32300,1893,UNNAMED,1893-08-18 00:00:00,46.1,-56.8,85,UNNAMED,2500,0,NaN,NaN,NaN,NaN
11,1893228N32300,1893,UNNAMED,1893-08-18 06:00:00,47.3,-54.7,80,UNNAMED,2500,0,NaN,NaN,NaN,NaN
12,1893228N32300,1893,UNNAMED,1893-08-18 12:00:00,48.4,-52.5,70,UNNAMED,2500,0,NaN,NaN,NaN,NaN
13,1893228N32300,1893,UNNAMED,1893-08-18 18:00:00,49.5,-49.7,65,UNNAMED,2500,0,NaN,NaN,NaN,NaN
14,1893228N32300,1893,UNNAMED,1893-08-19 00:00:00,50.5,-47.4,65,UNNAMED,2500,0,NaN,NaN,NaN,NaN
15,1893228N32300,1893,UNNAMED,1893-08-19 06:00:00,51.7,-44.5,65,UNNAMED,2500,0,NaN,NaN,NaN,NaN
16,1893271N16278,1893,UNNAMED,1893-09-27 12:00:00,16.4,-81.7,35,UNNAMED,2000,0,NaN,NaN,NaN,NaN
17,1893271N16278,1893,UNNAMED,1893-09-27 18:00:00,17.0,-82.6,40,UNNAMED,2000,0,NaN,NaN,NaN,NaN
18,1893271N16278,1893,UNNAMED,1893-09-28 00:00:00,17.7,-83.4,55,UNNAMED,2000,0,NaN,NaN,NaN,NaN
19,1893271N16278,1893,UNNAMED,1893-09-28 06:00:00,18.3,-84.2,65,UNNAMED,2000,0,NaN,NaN,NaN,NaN
20,1893271N16278,1893,UNNAMED,1893-09-28 12:00:00,19.0,-85.0,75,UNNAMED,2000,0,NaN,NaN,NaN,NaN
21,1893271N16278,1893,UNNAMED,1893-09-28 18:00:00,19.7,-85.8,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
22,1893271N16278,1893,UNNAMED,1893-09-29 00:00:00,20.3,-86.5,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
23,1893271N16278,1893,UNNAMED,1893-09-29 06:00:00,21.0,-87.3,80,UNNAMED,2000,0,NaN,NaN,NaN,NaN
24,1893271N16278,1893,UNNAMED,1893-09-29 12:00:00,21.7,-88.0,80,UNNAMED,2000,0,NaN,NaN,NaN,NaN
25,1893271N16278,1893,UNNAMED,1893-09-29 18:00:00,22.4,-88.7,80,UNNAMED,2000,0,NaN,NaN,NaN,NaN
26,1893271N16278,1893,UNNAMED,1893-09-30 00:00:00,23.1,-89.2,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
27,1893271N16278,1893,UNNAMED,1893-09-30 06:00:00,23.8,-89.7,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
28,1893271N16278,1893,UNNAMED,1893-09-30 12:00:00,24.5,-90.2,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
29,1893271N16278,1893,UNNAMED,1893-09-30 18:00:00,25.1,-90.6,85,UNNAMED,2000,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3869,2012296N14283,2012,SANDY,10/27/2012 6:00,28.1,-76.9,60,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3870,2012296N14283,2012,SANDY,10/27/2012 12:00,28.8,-76.5,70,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3871,2012296N14283,2012,SANDY,10/27/2012 18:00,29.7,-75.6,70,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3872,2012296N14283,2012,SANDY,10/28/2012 0:00,30.5,-74.7,65,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3873,2012296N14283,2012,SANDY,10/28/2012 6:00,31.3,-73.9,65,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3874,2012296N14283,2012,SANDY,10/28/2012 12:00,32.0,-73.0,65,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3875,2012296N14283,2012,SANDY,10/28/2012 18:00,32.8,-72.0,65,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3876,2012296N14283,2012,SANDY,10/29/2012 0:00,33.9,-71.0,70,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3877,2012296N14283,2012,SANDY,10/29/2012 6:00,35.3,-70.5,80,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3878,2012296N14283,2012,SANDY,10/29/2012 12:00,36.9,-71.0,85,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3879,2012296N14283,2012,SANDY,10/29/2012 18:00,38.3,-73.2,80,SANDY,147,75000,10/26/2012,10/24/2012,Mandatory,33.0
3880,2013255N19268,2013,INGRID,9/12/2013 18:00,19.7,-93.6,30,INGRID,23,1500,NaN,NaN,NaN,NaN
3881,2013255N19268,2013,INGRID,9/13/2013 0:00,19.7,-94.1,30,INGRID,23,1500,NaN,NaN,NaN,NaN
3882,2013255N19268,2013,INGRID,9/13/2013 6:00,19.6,-94.6,30,INGRID,23,1500,NaN,NaN,NaN,NaN
3883,2013255N19268,2013,INGRID,9/13/2013 12:00,19.3,-95.1,35,INGRID,23,1500,NaN,NaN,NaN,NaN
3884,2013255N19268,2013,INGRID,9/13/2013 18:00,19.1,-95.3,40,INGRID,23,1500,NaN,NaN,NaN,NaN
3885,2013255N19268,2013,INGRID,9/14/2013 0:00,19.3,-95.3,50,INGRID,23,1500,NaN,NaN,NaN,NaN
3886,2013255N19268,2013,INGRID,9/14/2013 6:00,19.6,-95.1,55,INGRID,23,1500,NaN,NaN,NaN,NaN
3887,2013255N19268,2013,INGRID,9/14/2013 12:00,20.3,-94.6,60,INGRID,23,1500,NaN,NaN,NaN,NaN
3888,2013255N19268,2013,INGRID,9/14/2013 18:00,21.0,-94.4,65,INGRID,23,1500,NaN,NaN,NaN,NaN
3889,2013255N19268,2013,INGRID,9/15/2013 0:00,21.6,-94.7,75,INGRID,23,1500,NaN,NaN,NaN,NaN
3890,2013255N19268,2013,INGRID,9/15/2013 6:00,22.0,-95.2,75,INGRID,23,1500,NaN,NaN,NaN,NaN
3891,2013255N19268,2013,INGRID,9/15/2013 12:00,22.4,-95.6,65,INGRID,23,1500,NaN,NaN,NaN,NaN
3892,2013255N19268,2013,INGRID,9/15/2013 18:00,22.7,-95.9,65,INGRID,23,1500,NaN,NaN,NaN,NaN
3893,2013255N19268,2013,INGRID,9/16/2013 0:00,23.0,-96.2,70,INGRID,23,1500,NaN,NaN,NaN,NaN
3894,2013255N19268,2013,INGRID,9/16/2013 6:00,23.4,-96.9,60,INGRID,23,1500,NaN,NaN,NaN,NaN
3895,2013255N19268,2013,INGRID,9/16/2013 11:15,23.7,-97.7,55,INGRID,23,1500,NaN,NaN,NaN,NaN
3896,2013255N19268,2013,INGRID,9/16/2013 12:00,23.7,-97.8,55,INGRID,23,1500,NaN,NaN,NaN,NaN
3897,2013255N19268,2013,INGRID,9/16/2013 18:00,23.7,-98.7,40,INGRID,23,1500,NaN,NaN,NaN,NaN
3898,2013255N19268,2013,INGRID,9/17/2013 0:00,23.7,-99.2,25,INGRID,23,1500,NaN,NaN,NaN,NaN

In [9]:
print(merged['SerialNum'].value_counts()[50:100])

2006237N13298    36
2003188N11307    36
1969226N18280    36
2005261N21290    35
1893271N16278    35
1972167N20271    35
1995271N19273    34
1971233N12313    34
2010255N13340    34
2012296N14283    33
1903252N21288    33
1985240N20286    33
1974258N15295    33
1993217N10320    33
2005236N23285    32
1994181N22276    32
1952295N11282    32
1995212N22287    30
2001255N26276    30
1909280N11284    30
1999286N16278    28
1985299N25270    27
2004223N11301    27
2007297N18300    27
2008203N18276    26
1990216N13281    25
1970212N19278    24
2007244N12303    22
2010247N15266    22
2004241N32282    21
1998252N26266    21
1991228N26286    21
1983228N27270    20
1961301N12279    20
2001157N28265    19
1938253N13314    19
2013255N19268    19
1957176N21267    19
2005185N18273    18
2012176N26272    18
1976219N26287    18
2005275N19274    17
1893228N32300    16
1989212N23270    16
1996279N23264    15
1989176N27264    14
1998244N22267    13
1919245N33287    12
1909264N21088     5
Name: SerialNum, dtype: int64

In [10]:
merged.to_csv (r'FilteredStorms.csv', index = None, header=True)